name: CI Build

# 触发条件：推送到 main 分支
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # 前端构建任务
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build frontend
        run: pnpm --filter frontend build:prod

  # 后端构建任务
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Check backend
        run: |
          cd packages/backend
          node index.js --version # 假设你加个简单的版本检查，或其他构建步骤
